# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in extism.gemspec
gemspec

gem "rake", "~> 13.0"
gem "ffi", "~> 1.15.5"

group :development do
  gem "yard", "~> 0.9.28"
  gem "rufo", "~> 0.13.0"
  gem "minitest", "~> 5.18.0"
end
