/* automatically generated by rust-bindgen 0.60.1 */

pub type __uint8_t = ::std::os::raw::c_uchar;
pub type __int32_t = ::std::os::raw::c_int;
pub type __uint64_t = ::std::os::raw::c_ulong;
pub type ExtismPlugin = i32;
pub type ExtismSize = u64;
extern "C" {
    pub fn extism_plugin_register(
        wasm: *const u8,
        wasm_size: ExtismSize,
        with_wasi: bool,
    ) -> ExtismPlugin;
}
extern "C" {
    pub fn extism_plugin_update(
        index: ExtismPlugin,
        wasm: *const u8,
        wasm_size: ExtismSize,
        with_wasi: bool,
    ) -> bool;
}
extern "C" {
    pub fn extism_plugin_config(
        plugin: ExtismPlugin,
        json: *const u8,
        json_size: ExtismSize,
    ) -> bool;
}
extern "C" {
    pub fn extism_function_exists(
        plugin: ExtismPlugin,
        func_name: *const ::std::os::raw::c_char,
    ) -> bool;
}
extern "C" {
    pub fn extism_call(
        plugin_id: ExtismPlugin,
        func_name: *const ::std::os::raw::c_char,
        data: *const u8,
        data_len: ExtismSize,
    ) -> i32;
}
extern "C" {
    pub fn extism_error(plugin: ExtismPlugin) -> *const ::std::os::raw::c_char;
}
extern "C" {
    pub fn extism_output_length(plugin: ExtismPlugin) -> ExtismSize;
}
extern "C" {
    pub fn extism_output_get(plugin: ExtismPlugin) -> *const u8;
}
extern "C" {
    pub fn extism_log_file(
        filename: *const ::std::os::raw::c_char,
        log_level: *const ::std::os::raw::c_char,
    ) -> bool;
}
