on:
  workflow_dispatch:

name: Release Elixir SDK

jobs:
  release-sdks:
    name: release-elixir
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download libextism
        uses: actions/download-artifact@v3
        with:
          name: libextism-${{ matrix.os }}
      - name: Install extism shared library
        shell: bash
        run: |
          sudo cp libextism.* /usr/local/lib
          sudo cp runtime/extism.h /usr/local/include

      - name: Setup Elixir Host SDK
        uses: erlef/setup-beam@v1
        with:
          experimental-otp: true
          otp-version: '25.0.4'
          elixir-version: '1.14.0'

      - name: Publish Elixir Host SDK to hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_PM_API_TOKEN }}
        run: |
          cd elixir
          cp ../LICENSE .
          make publish
  
