on:
  workflow_dispatch:

name: Release Node SDK

jobs:
  release-sdks:
    name: release-node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node env
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
          CI: true

      - name: Release Node Host SDK
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
          CI: true
        run: |
          cd node
          make publish
  
