on:
  workflow_dispatch:

name: Release extism-convert

jobs:
  release-convert:
    name: release-extism-convert
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust env
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Release Rust Convert Crate
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_API_TOKEN }}
        run: |
          cargo publish --manifest-path convert/Cargo.toml
