on:
  workflow_dispatch:

name: Release Haskell SDK

jobs:
  release-sdks:
    name: release-rust
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cachix/haskell-release-action@v1
        with:
          - hackage-token: "${{ secrets.HACKAGE_TOKEN }}"
          - work-dir: ./haskell
